name: Lint and test

on:
  pull_request:
    type: [opened, synchronize]

jobs:
  lint-and-test:
    name: Build, lint, and test package
    runs-on: ubuntu-latest

    steps:

      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup node and npm
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 20
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run linter
        run: yarn lint

      - name: Run tests
        run: yarn test